import stud1 from '../assets/stud1.png';
import stud2 from '../assets/stud2.png';
import stud3 from '../assets/stud3.png';
import stud4 from '../assets/stud4.png';
import stud5 from '../assets/stud5.png';
import stud6 from '../assets/stud6.png';
import stud7 from '../assets/stud7.png';
import stud8 from '../assets/stud8.png';
import stud9 from '../assets/stud9.png';
import stud10 from '../assets/stud10.png';
export const students = [
  {
    id: 1,
    name: 'Anjali Topno',
    profileImage: stud1,
    dob: 'Feb 14, 2012',
    phone: '1234567890',
    email: 'anjali@example.com',
    class: '5th',
    yearsInSchool: '2 years',
    guardian: {
      name: 'Guardian Name',
      phone: '1234567890',
      email: 'guardian@example.com',
    },
    familyMembers: [
      {
        firstName: 'John',
        lastName: 'Doe',
        phone: '9876543210',
        email: 'john@example.com',
      },
    ],
  },
  {
    id: 2,
    name: 'Rahul Sharma',
    profileImage: stud2,
    dob: 'Mar 5, 2011',
    phone: '9876543210',
    email: 'rahul@example.com',
    class: '6th',
    yearsInSchool: '3 years',
    guardian: {
      name: 'Guardian Sharma',
      phone: '9876543211',
      email: 'guardian.sharma@example.com',
    },
    familyMembers: [
      {
        firstName: 'Jane',
        lastName: 'Smith',
        phone: '9876501234',
        email: 'jane@example.com',
      },
    ],
  },
  {
    id: 3,
    name: 'Priya Singh',
    profileImage: stud3,
    dob: 'Dec 22, 2010',
    phone: '9876554321',
    email: 'priya@example.com',
    class: '7th',
    yearsInSchool: '4 years',
    guardian: {
      name: 'Guardian Singh',
      phone: '9876554320',
      email: 'guardian.singh@example.com',
    },
    familyMembers: [
      {
        firstName: 'Amit',
        lastName: 'Singh',
        phone: '9876521234',
        email: 'amit@example.com',
      },
    ],
  },
  {
    id: 4,
    name: 'Rohit Gupta',
    profileImage: stud4,
    dob: 'Jul 19, 2009',
    phone: '9876598765',
    email: 'rohit@example.com',
    class: '8th',
    yearsInSchool: '5 years',
    guardian: {
      name: 'Guardian Gupta',
      phone: '9876598764',
      email: 'guardian.gupta@example.com',
    },
    familyMembers: [
      {
        firstName: 'Meena',
        lastName: 'Gupta',
        phone: '9876509876',
        email: 'meena@example.com',
      },
    ],
  },
  {
    id: 5,
    name: 'Sneha Verma',
    profileImage: stud5,
    dob: 'Oct 10, 2013',
    phone: '9876512345',
    email: 'sneha@example.com',
    class: '4th',
    yearsInSchool: '1 year',
    guardian: {
      name: 'Guardian Verma',
      phone: '9876512340',
      email: 'guardian.verma@example.com',
    },
    familyMembers: [
      {
        firstName: 'Raj',
        lastName: 'Verma',
        phone: '9876523456',
        email: 'raj@example.com',
      },
    ],
  },
  {
    id: 6,
    name: 'Vikram Mehta',
    profileImage: stud6,
    dob: 'Nov 1, 2012',
    phone: '9876545678',
    email: 'vikram@example.com',
    class: '5th',
    yearsInSchool: '2 years',
    guardian: {
      name: 'Guardian Mehta',
      phone: '9876545677',
      email: 'guardian.mehta@example.com',
    },
    familyMembers: [
      {
        firstName: 'Ritu',
        lastName: 'Mehta',
        phone: '9876545689',
        email: 'ritu@example.com',
      },
    ],
  },
  {
    id: 7,
    name: 'Aarav Jain',
    profileImage: stud7,
    dob: 'Apr 15, 2010',
    phone: '9876598761',
    email: 'aarav@example.com',
    class: '7th',
    yearsInSchool: '4 years',
    guardian: {
      name: 'Guardian Jain',
      phone: '9876598762',
      email: 'guardian.jain@example.com',
    },
    familyMembers: [
      {
        firstName: 'Karan',
        lastName: 'Jain',
        phone: '9876598763',
        email: 'karan@example.com',
      },
    ],
  },
  {
    id: 8,
    name: 'Isha Roy',
    profileImage: stud8,
    dob: 'Jan 18, 2011',
    phone: '9876510987',
    email: 'isha@example.com',
    class: '6th',
    yearsInSchool: '3 years',
    guardian: {
      name: 'Guardian Roy',
      phone: '9876510988',
      email: 'guardian.roy@example.com',
    },
    familyMembers: [
      {
        firstName: 'Sima',
        lastName: 'Roy',
        phone: '9876510989',
        email: 'sima@example.com',
      },
    ],
  },
  {
    id: 9,
    name: 'Kabir Khan',
    profileImage: stud9,
    dob: 'Jun 7, 2008',
    phone: '9876543212',
    email: 'kabir@example.com',
    class: '9th',
    yearsInSchool: '6 years',
    guardian: {
      name: 'Guardian Khan',
      phone: '9876543211',
      email: 'guardian.khan@example.com',
    },
    familyMembers: [
      {
        firstName: 'Ayesha',
        lastName: 'Khan',
        phone: '9876543213',
        email: 'ayesha@example.com',
      },
    ],
  },
  {
    id: 10,
    name: 'Simran Kaur',
    profileImage: stud10,
    dob: 'Sep 25, 2013',
    phone: '9876521098',
    email: 'simran@example.com',
    class: '4th',
    yearsInSchool: '1 year',
    guardian: {
      name: 'Guardian Kaur',
      phone: '9876521099',
      email: 'guardian.kaur@example.com',
    },
    familyMembers: [
      {
        firstName: 'Harpreet',
        lastName: 'Kaur',
        phone: '9876521100',
        email: 'harpreet@example.com',
      },
    ],
  },
  {
    id: 11,
    name: 'Arjun Desai',
    profileImage: stud3,
    dob: 'May 12, 2012',
    phone: '7890123456',
    email: 'arjun@example.com',
    class: '5th',
    yearsInSchool: '2 years',
    guardian: {
      name: 'Guardian Desai',
      phone: '7890123457',
      email: 'guardian.desai@example.com',
    },
    familyMembers: [
      {
        firstName: 'Mohan',
        lastName: 'Desai',
        phone: '7890123458',
        email: 'mohan@example.com',
      },
    ],
  },
  {
    id: 12,
    name: 'Nikita Rao',
    profileImage: stud4,
    dob: 'Dec 15, 2010',
    phone: '6789012345',
    email: 'nikita@example.com',
    class: '7th',
    yearsInSchool: '4 years',
    guardian: {
      name: 'Guardian Rao',
      phone: '6789012346',
      email: 'guardian.rao@example.com',
    },
    familyMembers: [
      {
        firstName: 'Sunita',
        lastName: 'Rao',
        phone: '6789012347',
        email: 'sunita@example.com',
      },
    ],
  },
  {
    id: 13,
    name: 'Tanya Bhatia',
    profileImage: stud5,
    dob: 'Aug 28, 2009',
    phone: '5678901234',
    email: 'tanya@example.com',
    class: '8th',
    yearsInSchool: '5 years',
    guardian: {
      name: 'Guardian Bhatia',
      phone: '5678901235',
      email: 'guardian.bhatia@example.com',
    },
    familyMembers: [
      {
        firstName: 'Rajesh',
        lastName: 'Bhatia',
        phone: '5678901236',
        email: 'rajesh@example.com',
      },
    ],
  },
  {
    id: 14,
    name: 'Aryan Nair',
    profileImage: stud6,
    dob: 'Jul 3, 2008',
    phone: '4567890123',
    email: 'aryan@example.com',
    class: '9th',
    yearsInSchool: '6 years',
    guardian: {
      name: 'Guardian Nair',
      phone: '4567890124',
      email: 'guardian.nair@example.com',
    },
    familyMembers: [
      {
        firstName: 'Kiran',
        lastName: 'Nair',
        phone: '4567890125',
        email: 'kiran@example.com',
      },
    ],
  },
  {
    id: 15,
    name: 'Sana Sheikh',
    profileImage: stud7,
    dob: 'Nov 23, 2013',
    phone: '3456789012',
    email: 'sana@example.com',
    class: '4th',
    yearsInSchool: '1 year',
    guardian: {
      name: 'Guardian Sheikh',
      phone: '3456789013',
      email: 'guardian.sheikh@example.com',
    },
    familyMembers: [
      {
        firstName: 'Faheem',
        lastName: 'Sheikh',
        phone: '3456789014',
        email: 'faheem@example.com',
      },
    ],
  },
  {
    id: 16,
    name: 'Riya Malik',
    profileImage: stud8,
    dob: 'Oct 11, 2010',
    phone: '2345678901',
    email: 'riya@example.com',
    class: '7th',
    yearsInSchool: '3 years',
    guardian: {
      name: 'Guardian Malik',
      phone: '2345678902',
      email: 'guardian.malik@example.com',
    },
    familyMembers: [
      {
        firstName: 'Anil',
        lastName: 'Malik',
        phone: '2345678903',
        email: 'anil@example.com',
      },
    ],
  },
  {
    id: 17,
    name: 'Ishan Tiwari',
    profileImage: stud9,
    dob: 'May 27, 2009',
    phone: '3456789012',
    email: 'ishan@example.com',
    class: '8th',
    yearsInSchool: '5 years',
    guardian: {
      name: 'Guardian Tiwari',
      phone: '3456789013',
      email: 'guardian.tiwari@example.com',
    },
    familyMembers: [
      {
        firstName: 'Rohini',
        lastName: 'Tiwari',
        phone: '3456789014',
        email: 'rohini@example.com',
      },
    ],
  },
  {
    id: 18,
    name: 'Meera Chaudhary',
    profileImage: stud10,
    dob: 'Feb 3, 2012',
    phone: '4567890123',
    email: 'meera@example.com',
    class: '5th',
    yearsInSchool: '2 years',
    guardian: {
      name: 'Guardian Chaudhary',
      phone: '4567890124',
      email: 'guardian.chaudhary@example.com',
    },
    familyMembers: [
      {
        firstName: 'Arjun',
        lastName: 'Chaudhary',
        phone: '4567890125',
        email: 'arjun@example.com',
      },
    ],
  },
  {
    id: 19,
    name: 'Aditya Kapoor',
    profileImage: stud1,
    dob: 'Dec 29, 2011',
    phone: '5678901234',
    email: 'aditya@example.com',
    class: '6th',
    yearsInSchool: '3 years',
    guardian: {
      name: 'Guardian Kapoor',
      phone: '5678901235',
      email: 'guardian.kapoor@example.com',
    },
    familyMembers: [
      {
        firstName: 'Nisha',
        lastName: 'Kapoor',
        phone: '5678901236',
        email: 'nisha@example.com',
      },
    ],
  },
  {
    id: 20,
    name: 'Pooja Mishra',
    profileImage: stud2,
    dob: 'Jul 14, 2013',
    phone: '6789012345',
    email: 'pooja@example.com',
    class: '4th',
    yearsInSchool: '1 year',
    guardian: {
      name: 'Guardian Mishra',
      phone: '6789012346',
      email: 'guardian.mishra@example.com',
    },
    familyMembers: [
      {
        firstName: 'Amit',
        lastName: 'Mishra',
        phone: '6789012347',
        email: 'amit@example.com',
      },
    ],
  },
];
